### ISSUE TITLE
fpn.pytorch/lib/model/nms/src/nms_cuda.c: No such file or directory

### ISSUE THREAD

**Issue by Feynman27** [jwyang/fpn.pytorch#1]
When running `make.sh`, I'm getting a `no such file or directory` error for the file `nms_cuda.c`. This 
appears to be missing from the `lib/model/nms/src` directory. 

```bash
running build_ext
building '_nms' extension
creating home
creating home/thomasbalestri
creating home/thomasbalestri/PycharmProjects
creating home/thomasbalestri/PycharmProjects/fpn.pytorch
creating home/thomasbalestri/PycharmProjects/fpn.pytorch/lib
creating home/thomasbalestri/PycharmProjects/fpn.pytorch/lib/model
creating home/thomasbalestri/PycharmProjects/fpn.pytorch/lib/model/nms
creating home/thomasbalestri/PycharmProjects/fpn.pytorch/lib/model/nms/src
gcc -pthread -B /home/thomasbalestri/anaconda3/envs/pytorch0.3.0_py2/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/thomasbalestri/anaconda3/envs/pytorch0.3.0_py2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/thomasbalestri/anaconda3/envs/pytorch0.3.0_py2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/thomasbalestri/anaconda3/envs/pytorch0.3.0_py2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/thomasbalestri/anaconda3/envs/pytorch0.3.0_py2/include/python2.7 -c _nms.c -o ./_nms.o
gcc -pthread -B /home/thomasbalestri/anaconda3/envs/pytorch0.3.0_py2/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/thomasbalestri/anaconda3/envs/pytorch0.3.0_py2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/thomasbalestri/anaconda3/envs/pytorch0.3.0_py2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/thomasbalestri/anaconda3/envs/pytorch0.3.0_py2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/thomasbalestri/anaconda3/envs/pytorch0.3.0_py2/include/python2.7 -c /home/thomasbalestri/PycharmProjects/fpn.pytorch/lib/model/nms/src/nms_cuda.c -o ./home/thomasbalestri/PycharmProjects/fpn.pytorch/lib/model/nms/src/nms_cuda.o
gcc: error: /home/thomasbalestri/PycharmProjects/fpn.pytorch/lib/model/nms/src/nms_cuda.c: No such file or directory
Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "/home/thomasbalestri/anaconda3/envs/pytorch0.3.0_py2/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 167, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/thomasbalestri/anaconda3/envs/pytorch0.3.0_py2/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 103, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/thomasbalestri/anaconda3/envs/pytorch0.3.0_py2/lib/python2.7/site-packages/cffi/api.py", line 690, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/thomasbalestri/anaconda3/envs/pytorch0.3.0_py2/lib/python2.7/site-packages/cffi/recompiler.py", line 1513, in recompile
    compiler_verbose, debug)
  File "/home/thomasbalestri/anaconda3/envs/pytorch0.3.0_py2/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/thomasbalestri/anaconda3/envs/pytorch0.3.0_py2/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1

```

**Comment by Feynman27** [comment]
I assume it's the same src file located [here.](https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/model/nms/src/nms_cuda.c).

**Comment by jwyang** [comment]
@Feynman27 , yes, it should be that source file, I will add it here.

**Comment by Feynman27** [comment]
Great, thanks! Closing this issue.
