### ISSUE TITLE
Training suddenly terminates with run time error, please help

### ISSUE THREAD

**Issue by Karthik-Suresh93** [jwyang/fpn.pytorch#13]
[session 1][epoch  1][iter 2100] loss: 1.2515, lr: 1.00e-03
			fg/bg=(32/96), time cost: 46.959169
			rpn_cls: 0.0647, rpn_box: 0.0156, rcnn_cls: 0.7545, rcnn_box 0.4920
[session 1][epoch  1][iter 2200] loss: 1.3776, lr: 1.00e-03
			fg/bg=(32/96), time cost: 46.760157
			rpn_cls: 0.2410, rpn_box: 0.1341, rcnn_cls: 0.7460, rcnn_box 0.3669
Traceback (most recent call last):
  File "trainval_net.py", line 330, in <module>
    roi_labels = FPN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/k21993/anaconda3/envs/python27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/k21993/anaconda3/envs/python27/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 60, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/k21993/anaconda3/envs/python27/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 70, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/k21993/anaconda3/envs/python27/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 67, in parallel_apply
    raise output
RuntimeError: invalid argument 3: expecting vector of indices at /opt/conda/conda-bld/pytorch_1503966894950/work/torch/lib/THC/generic/THCTensorIndex.cu:4

**Comment by KevinQian97** [comment]
I have encountered with the same problem. Have you found out how to solve it?

**Comment by KevinQian97** [comment]
I am not sure if it's because of the version of pytorch

**Comment by KevinQian97** [comment]
I found that the code runs normally on faster-rcnn. But if I use the code of fpn, it failed. So I guess the problem happens in fpn.py, but I still can't find out why.
What's more, I used this model to train my personal data, if I changed the data back to origin Voc2007, it works. That's strange. I just changed my personal data into the form of Voc2007.
Here is one of my annotation file:
<annotation>
  <folder>train</folder>
  <filename>VIRAT_S_000000.mp4_0</filename>
  <path>C:/Users/Kevin Qian/Downloads/images/train/VIRAT_S_000000.mp4_0.jpg</path>
  <source>
    <database>Unknown</database>
  </source>
  <size>
    <width>1920</width>
    <height>1080</height>
    <depth>3</depth>
  </size>
  <segmented>0</segmented>
  <object>
    <name>Other</name>
    <difficult>0</difficult>
    <bndbox>
      <xmin>636</xmin>
      <ymin>723</ymin>
      <xmax>655</xmax>
      <ymax>787</ymax>
    </bndbox>
  </object>
  <object>
    <name>Other</name>
    <difficult>0</difficult>
    <bndbox>
      <xmin>411</xmin>
      <ymin>618</ymin>
      <xmax>438</xmax>
      <ymax>703</ymax>
    </bndbox>
  </object>
  <object>
    <name>Person</name>
    <difficult>0</difficult>
    <bndbox>
      <xmin>349</xmin>
      <ymin>709</ymin>
      <xmax>410</xmax>
      <ymax>850</ymax>
    </bndbox>
  </object>
  <object>
    <name>Other</name>
    <difficult>0</difficult>
    <bndbox>
      <xmin>760</xmin>
      <ymin>758</ymin>
      <xmax>778</xmax>
      <ymax>831</ymax>
    </bndbox>
  </object>
  <object>
    <name>Person</name>
    <difficult>0</difficult>
    <bndbox>
      <xmin>1386</xmin>
      <ymin>245</ymin>
      <xmax>1432</xmax>
      <ymax>354</ymax>
    </bndbox>
  </object>
  <object>
    <name>Person</name>
    <difficult>0</difficult>
    <bndbox>
      <xmin>276</xmin>
      <ymin>688</ymin>
      <xmax>345</xmax>
      <ymax>845</ymax>
    </bndbox>
  </object>
  <object>
    <name>Other</name>
    <difficult>0</difficult>
    <bndbox>
      <xmin>512</xmin>
      <ymin>687</ymin>
      <xmax>541</xmax>
      <ymax>747</ymax>
    </bndbox>
  </object>
</annotation>

and here is the annotation file in original voc2007
<annotation>
	<folder>VOC2007</folder>
	<filename>009962.jpg</filename>
	<source>
		<database>The VOC2007 Database</database>
		<annotation>PASCAL VOC2007</annotation>
		<image>flickr</image>
		<flickrid>246788553</flickrid>
	</source>
	<owner>
		<flickrid>Tool - Wroclaw</flickrid>
		<name>Milosz J.</name>
	</owner>
	<size>
		<width>500</width>
		<height>375</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>chair</name>
		<pose>Right</pose>
		<truncated>1</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>211</xmin>
			<ymin>192</ymin>
			<xmax>324</xmax>
			<ymax>326</ymax>
		</bndbox>
	</object>
	<object>
		<name>person</name>
		<pose>Unspecified</pose>
		<truncated>1</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>162</xmin>
			<ymin>72</ymin>
			<xmax>273</xmax>
			<ymax>248</ymax>
		</bndbox>
	</object>
	<object>
		<name>person</name>
		<pose>Right</pose>
		<truncated>1</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>250</xmin>
			<ymin>68</ymin>
			<xmax>473</xmax>
			<ymax>312</ymax>
		</bndbox>
	</object>
	<object>
		<name>person</name>
		<pose>Right</pose>
		<truncated>1</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>4</xmin>
			<ymin>2</ymin>
			<xmax>253</xmax>
			<ymax>374</ymax>
		</bndbox>
	</object>
	<object>
		<name>diningtable</name>
		<pose>Unspecified</pose>
		<truncated>1</truncated>
		<difficult>1</difficult>
		<bndbox>
			<xmin>358</xmin>
			<ymin>216</ymin>
			<xmax>500</xmax>
			<ymax>375</ymax>
		</bndbox>
	</object>
</annotation>
