### ISSUE TITLE
dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by CXY573** [jwyang/fpn.pytorch#30]
Traceback (most recent call last):
  File "trainval_net.py", line 330, in <module>
    roi_labels = FPN(im_data, im_info, gt_boxes, num_boxes)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pci/save/Technology/Part-B/FPN/lib/model/fpn/fpn.py", line 187, in forward
    rois, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(rpn_feature_maps, im_info, gt_boxes, num_boxes)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pci/save/Technology/Part-B/FPN/lib/model/rpn/rpn_fpn.py", line 100, in forward
    im_info, cfg_key, rpn_shapes))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pci/save/Technology/Part-B/FPN/lib/model/rpn/proposal_layer_fpn.py", line 122, in forward
    output[i,:num_proposal,1:] = proposals_single
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by planckztd** [comment]
the same problem,we need some help @CXY573

**Comment by tsoi2** [comment]
same problem, but encountered in 
File "/home/tsoikawai/OIC_2018/faster-rcnn.pytorch/lib/model/rpn/proposal_layer.py", line 159
when running 'test_net.py'

I fixed this issue by adding '--cuda' in the command line argument when running 'test_net.py'
