### ISSUE TITLE
COMPILEERROR（I already change the sm_61 but error  still happened）

### ISSUE THREAD

**Issue by yuyijie1995** [jwyang/fpn.pytorch#32]
Traceback (most recent call last):
  File "build.py", line 35, in <module>
    ffi.build()
  File "/home/wrc/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/wrc/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/wrc/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/wrc/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/wrc/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/wrc/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1

**Comment by youngYMR** [comment]
I met the same problem.Have you solved it?

**Comment by John-Rocker** [comment]
same error.Who can answer the question?

**Comment by yuyijie1995** [comment]
I have no idea

**Comment by SJTU-Applemin** [comment]
I met the same problem when compiling. Who can help with this problem?

**Comment by salt-fisher** [comment]
the same problem exists in the project [issues](https://github.com/jwyang/faster-rcnn.pytorch/issues/235),change your pytorch version to 0.4.0 seems to be useful

**Comment by JackJWWong** [comment]
you could try python2.7, I used python 2.7 and complied with no issues
